package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTbProject<M extends BaseTbProject<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setOs(java.lang.String os) {
		set("os", os);
	}
	
	public java.lang.String getOs() {
		return getStr("os");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setRelatedId(java.lang.Integer relatedId) {
		set("relatedId", relatedId);
	}
	
	public java.lang.Integer getRelatedId() {
		return getInt("relatedId");
	}

	public void setSubProjectJson(java.lang.String subProjectJson) {
		set("subProjectJson", subProjectJson);
	}
	
	public java.lang.String getSubProjectJson() {
		return getStr("subProjectJson");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setDutyPerson(java.lang.String dutyPerson) {
		set("dutyPerson", dutyPerson);
	}
	
	public java.lang.String getDutyPerson() {
		return getStr("dutyPerson");
	}

	public void setSshAccountId(java.lang.Integer sshAccountId) {
		set("sshAccountId", sshAccountId);
	}
	
	public java.lang.Integer getSshAccountId() {
		return getInt("sshAccountId");
	}

	public void setEdasAppId(java.lang.String edasAppId) {
		set("edasAppId", edasAppId);
	}
	
	public java.lang.String getEdasAppId() {
		return getStr("edasAppId");
	}

	public void setEdasPackageVersion(java.lang.String edasPackageVersion) {
		set("edasPackageVersion", edasPackageVersion);
	}
	
	public java.lang.String getEdasPackageVersion() {
		return getStr("edasPackageVersion");
	}

	public void setEadsAccountId(java.lang.Integer eadsAccountId) {
		set("eadsAccountId", eadsAccountId);
	}
	
	public java.lang.Integer getEadsAccountId() {
		return getInt("eadsAccountId");
	}

	public void setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
	}
	
	public java.lang.Integer getAccountId() {
		return getInt("accountId");
	}

	public void setScmPath(java.lang.String scmPath) {
		set("scmPath", scmPath);
	}
	
	public java.lang.String getScmPath() {
		return getStr("scmPath");
	}

	public void setScriptFilePath(java.lang.String scriptFilePath) {
		set("scriptFilePath", scriptFilePath);
	}
	
	public java.lang.String getScriptFilePath() {
		return getStr("scriptFilePath");
	}

	public void setSshScript(java.lang.String sshScript) {
		set("sshScript", sshScript);
	}
	
	public java.lang.String getSshScript() {
		return getStr("sshScript");
	}

	public void setScript(java.lang.String script) {
		set("script", script);
	}
	
	public java.lang.String getScript() {
		return getStr("script");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
