package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTbStep<M extends BaseTbStep<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setProjectId(java.lang.Integer projectId) {
		set("projectId", projectId);
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("projectId");
	}

	public void setBuildId(java.lang.Integer buildId) {
		set("buildId", buildId);
	}
	
	public java.lang.Integer getBuildId() {
		return getInt("buildId");
	}

	public void setPreviousStepId(java.lang.Integer previousStepId) {
		set("previousStepId", previousStepId);
	}
	
	public java.lang.Integer getPreviousStepId() {
		return getInt("previousStepId");
	}

	public void setNextStepId(java.lang.Integer nextStepId) {
		set("nextStepId", nextStepId);
	}
	
	public java.lang.Integer getNextStepId() {
		return getInt("nextStepId");
	}

	public void setOrder(java.lang.Integer order) {
		set("order", order);
	}
	
	public java.lang.Integer getOrder() {
		return getInt("order");
	}

	public void setOutPut(java.lang.String outPut) {
		set("outPut", outPut);
	}
	
	public java.lang.String getOutPut() {
		return getStr("outPut");
	}

	public void setStartTime(java.util.Date startTime) {
		set("startTime", startTime);
	}
	
	public java.util.Date getStartTime() {
		return get("startTime");
	}

	public void setEndTime(java.util.Date endTime) {
		set("endTime", endTime);
	}
	
	public java.util.Date getEndTime() {
		return get("endTime");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
