package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("blog", "id", Blog.class);
		arp.addMapping("tb_account", "id", TbAccount.class);
		arp.addMapping("tb_build", "id", TbBuild.class);
		arp.addMapping("tb_env_config", "id", TbEnvConfig.class);
		arp.addMapping("tb_project", "id", TbProject.class);
		arp.addMapping("tb_step", "id", TbStep.class);
		arp.addMapping("tb_template", "id", TbTemplate.class);
	}
}

