package com.demo.common.model;

import com.demo.common.model.base.BaseTbAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbAccount extends BaseTbAccount<TbAccount> {
	
}
