package com.demo.common.model;

import com.alibaba.fastjson.JSON;
import com.demo.common.model.base.BaseTbBuild;
import com.demo.util.websocket.MyWebSocketClient;
import com.demo.util.websocket.model.CommandType;
import com.demo.util.websocket.model.GroupMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbBuild extends BaseTbBuild<TbBuild> {
    public static final String  line = "<br/>";

    MyWebSocketClient myWebSocketClient;
    String groupId;

    /**
     * 追加内容
     * @param msg
     */
    public void appendOutput(String msg){
        this.setTriggerDesc(this.getTriggerDesc()+msg+line);
        this.update();
        myWebSocketClient.send(JSON.toJSONString(new GroupMessage(this.groupId,msg,CommandType.groupMessage)));
    }
    public void appendOutputNoBR(String msg){
        this.setTriggerDesc(this.getTriggerDesc()+msg+" ");
        this.update();
        myWebSocketClient.send(JSON.toJSONString(new GroupMessage(this.groupId,msg,CommandType.groupMessage)));
    }

    public MyWebSocketClient getMyWebSocketClient() {
        return myWebSocketClient;
    }

    public void setMyWebSocketClient(MyWebSocketClient myWebSocketClient) {
        this.myWebSocketClient = myWebSocketClient;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getGroupId() {
        return groupId;
    }
}
