package com.demo.common.model;

import com.demo.common.model.base.BaseTbEnvConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbEnvConfig extends BaseTbEnvConfig<TbEnvConfig> {
	
}
