package com.demo.common.model;

import com.demo.common.model.base.BaseTbTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbTemplate extends BaseTbTemplate<TbTemplate> {
	
}
