package com.demo.common.model;

import com.demo.common.model.base.BaseTbTopology;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbTopology extends BaseTbTopology<TbTopology> {
	
}
