package com.demo.common.model;

import com.demo.common.model.base.BaseTbWeekReport;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbWeekReport extends BaseTbWeekReport<TbWeekReport> {
	
}
